import { Region, Position, PoliticalParty, ElectedOfficial, Announcement } from './api';

export const mockRegions: Region[] = [
  { id: 1, name: "N'Djamena", code: "NDJ", isActive: true, displayOrder: 1 },
  { id: 2, name: "Logone Occidental", code: "LO", isActive: true, displayOrder: 2 },
  { id: 3, name: "Logone Oriental", code: "LOR", isActive: true, displayOrder: 3 },
  { id: 4, name: "Mayo-Kebbi Est", code: "MKE", isActive: true, displayOrder: 4 },
  { id: 5, name: "Mayo-Kebbi Ouest", code: "MKO", isActive: true, displayOrder: 5 },
  { id: 6, name: "Moyen-Chari", code: "MC", isActive: true, displayOrder: 6 },
  { id: 7, name: "Chari-Baguirmi", code: "CB", isActive: true, displayOrder: 7 },
  { id: 8, name: "Lac", code: "LAC", isActive: true, displayOrder: 8 },
  { id: 9, name: "Salamat", code: "SAL", isActive: true, displayOrder: 9 },
  { id: 10, name: "Borkou", code: "BOR", isActive: true, displayOrder: 10 },
];

export const mockPositions: Position[] = [
  { id: 1, name: "President", code: "PRES", level: "National", isActive: true, displayOrder: 1 },
  { id: 2, name: "Prime Minister", code: "PM", level: "National", isActive: true, displayOrder: 2 },
  { id: 3, name: "Senator", code: "SEN", level: "National", isActive: true, displayOrder: 3 },
  { id: 4, name: "Deputy", code: "DEP", level: "National", isActive: true, displayOrder: 4 },
  { id: 5, name: "Minister", code: "MIN", level: "National", isActive: true, displayOrder: 5 },
  { id: 6, name: "Governor", code: "GOV", level: "Regional", isActive: true, displayOrder: 6 },
  { id: 7, name: "Mayor", code: "MAY", level: "Local", isActive: true, displayOrder: 7 },
  { id: 8, name: "Prefect", code: "PRE", level: "Regional", isActive: true, displayOrder: 8 },
];

export const mockPoliticalParties: PoliticalParty[] = [
  { id: 1, name: "Mouvement Patriotique du Salut", abbreviation: "MPS", color: "#002664", isActive: true, displayOrder: 1 },
  { id: 2, name: "Union Nationale pour la Démocratie et le Renouveau", abbreviation: "UNDR", color: "#C41E3A", isActive: true, displayOrder: 2 },
  { id: 3, name: "Rassemblement pour la Démocratie et le Progrès", abbreviation: "RDP", color: "#006B3F", isActive: true, displayOrder: 3 },
  { id: 4, name: "Front d'Action pour la République", abbreviation: "FAR", color: "#FFA500", isActive: true, displayOrder: 4 },
  { id: 5, name: "Parti pour les Libertés et le Développement", abbreviation: "PLD", color: "#0052A5", isActive: true, displayOrder: 5 },
  { id: 6, name: "Union pour le Renouveau et la Démocratie", abbreviation: "URD", color: "#8B4513", isActive: true, displayOrder: 6 },
];

export const mockOfficials: ElectedOfficial[] = [
  {
    id: 1,
    firstName: "Mahamat",
    lastName: "Idriss Déby",
    region: mockRegions[0],
    district: "National",
    position: mockPositions[0],
    politicalParty: mockPoliticalParties[0],
    biography: "President of the Republic of Chad since 2021. Military officer and politician who has led significant reforms in governance and national security.",
    termStart: "2021-04-20",
    email: "president@tchad.gov.td",
    phone: "+235 22 51 44 37",
    verified: true,
    published: true,
  },
  {
    id: 2,
    firstName: "Succès",
    lastName: "Masra",
    region: mockRegions[0],
    district: "National",
    position: mockPositions[1],
    politicalParty: mockPoliticalParties[1],
    biography: "Prime Minister appointed in 2024. Former opposition leader known for advocating democratic reforms and youth empowerment.",
    termStart: "2024-01-01",
    email: "pm@tchad.gov.td",
    phone: "+235 22 51 50 15",
    verified: true,
    published: true,
  },
  {
    id: 3,
    firstName: "Haroun",
    lastName: "Kabadi",
    region: mockRegions[1],
    district: "Moundou",
    position: mockPositions[3],
    politicalParty: mockPoliticalParties[0],
    biography: "Deputy representing Moundou constituency. Former Minister of Sports and advocate for youth development programs.",
    termStart: "2020-01-15",
    termEnd: "2025-01-15",
    email: "h.kabadi@assemblee.td",
    phone: "+235 66 12 34 56",
    verified: true,
    published: true,
  },
  {
    id: 4,
    firstName: "Amina",
    lastName: "Hassan",
    region: mockRegions[2],
    district: "Doba",
    position: mockPositions[2],
    politicalParty: mockPoliticalParties[2],
    biography: "Senator and women's rights advocate. Leading voice for gender equality and education reform in Chad.",
    termStart: "2021-06-01",
    termEnd: "2027-06-01",
    email: "a.hassan@senat.td",
    phone: "+235 66 23 45 67",
    verified: true,
    published: true,
  },
  {
    id: 5,
    firstName: "Abdoulaye",
    lastName: "Sabre",
    region: mockRegions[3],
    district: "Bongor",
    position: mockPositions[4],
    politicalParty: mockPoliticalParties[0],
    biography: "Minister of Agriculture and Environment. Expert in sustainable farming practices and climate adaptation strategies.",
    termStart: "2022-03-10",
    email: "minister.agriculture@tchad.gov.td",
    phone: "+235 22 51 60 20",
    verified: true,
    published: true,
  },
  {
    id: 6,
    firstName: "Fatima",
    lastName: "Mahamat",
    region: mockRegions[0],
    district: "N'Djamena 1",
    position: mockPositions[6],
    politicalParty: mockPoliticalParties[3],
    biography: "Mayor of N'Djamena's 1st arrondissement. Urban planning specialist focused on infrastructure development and public services.",
    termStart: "2021-11-20",
    termEnd: "2026-11-20",
    email: "maire.ndj1@mairie.td",
    phone: "+235 66 34 56 78",
    verified: true,
    published: true,
  },
  {
    id: 7,
    firstName: "Ibrahim",
    lastName: "Youssouf",
    region: mockRegions[4],
    district: "Pala",
    position: mockPositions[5],
    politicalParty: mockPoliticalParties[0],
    biography: "Governor of Mayo-Kebbi Ouest. Former military officer with extensive experience in regional administration and security.",
    termStart: "2020-08-15",
    email: "gov.mko@tchad.gov.td",
    phone: "+235 69 12 34 56",
    verified: true,
    published: true,
  },
  {
    id: 8,
    firstName: "Mariam",
    lastName: "Oumar",
    region: mockRegions[5],
    district: "Sarh",
    position: mockPositions[3],
    politicalParty: mockPoliticalParties[4],
    biography: "Deputy for Sarh constituency. Healthcare professional advocating for improved medical services in rural areas.",
    termStart: "2020-01-15",
    termEnd: "2025-01-15",
    email: "m.oumar@assemblee.td",
    phone: "+235 66 45 67 89",
    verified: true,
    published: true,
  },
  {
    id: 9,
    firstName: "Ali",
    lastName: "Ahmed",
    region: mockRegions[6],
    district: "Massenya",
    position: mockPositions[7],
    politicalParty: mockPoliticalParties[5],
    biography: "Prefect of Massenya. Education advocate working to improve school infrastructure and teacher training programs.",
    termStart: "2021-04-01",
    email: "prefet.massenya@tchad.gov.td",
    phone: "+235 66 56 78 90",
    verified: true,
    published: true,
  },
  {
    id: 10,
    firstName: "Khadija",
    lastName: "Abdallah",
    region: mockRegions[7],
    district: "Bol",
    position: mockPositions[2],
    politicalParty: mockPoliticalParties[1],
    biography: "Senator representing Lac region. Environmental activist focused on Lake Chad conservation and sustainable fishing practices.",
    termStart: "2021-06-01",
    termEnd: "2027-06-01",
    email: "k.abdallah@senat.td",
    phone: "+235 66 67 89 01",
    verified: true,
    published: true,
  },
  {
    id: 11,
    firstName: "Moussa",
    lastName: "Ibrahim",
    region: mockRegions[8],
    district: "Am Timan",
    position: mockPositions[3],
    politicalParty: mockPoliticalParties[2],
    biography: "Deputy for Am Timan. Former journalist advocating for press freedom and transparency in government.",
    termStart: "2020-01-15",
    termEnd: "2025-01-15",
    email: "m.ibrahim@assemblee.td",
    phone: "+235 66 78 90 12",
    verified: true,
    published: true,
  },
  {
    id: 12,
    firstName: "Aïcha",
    lastName: "Mahamat",
    region: mockRegions[9],
    district: "Faya-Largeau",
    position: mockPositions[5],
    politicalParty: mockPoliticalParties[0],
    biography: "Governor of Borkou region. Economic development specialist working to boost tourism and mining sectors.",
    termStart: "2022-02-01",
    email: "gov.borkou@tchad.gov.td",
    phone: "+235 69 89 01 23",
    verified: true,
    published: true,
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 1,
    title: "National Education Reform Initiative Launched",
    content: "<p>The Ministry of Education has launched a comprehensive reform initiative aimed at improving educational quality across all regions. The program includes teacher training, infrastructure development, and curriculum modernization.</p><p>Key focus areas include expanding access to secondary education in rural areas and integrating technology into classrooms nationwide.</p>",
    tags: ["Education", "Reform", "Development"],
    publishDate: "2024-12-15T08:00:00Z",
    isPublished: true,
  },
  {
    id: 2,
    title: "Healthcare Services Expansion in Rural Regions",
    content: "<p>New healthcare centers are being established in 15 rural districts to improve access to medical services. The initiative includes mobile clinics and telemedicine capabilities.</p>",
    tags: ["Healthcare", "Rural Development"],
    externalLink: "https://www.africa.engineering.cmu.edu/admissions/index.html",
    publishDate: "2024-12-10T10:30:00Z",
    isPublished: true,
  },
  {
    id: 3,
    title: "Infrastructure Development Plan for 2025 Announced",
    content: "<p>The government has unveiled an ambitious infrastructure plan focusing on road networks, water supply systems, and electrification projects across all regions.</p><p>Investment of over 500 billion CFA francs allocated for the first phase.</p>",
    tags: ["Infrastructure", "Development", "Investment"],
    publishDate: "2024-12-08T14:00:00Z",
    isPublished: true,
  },
  {
    id: 4,
    title: "Youth Employment Program Registration Opens",
    content: "<p>Registration is now open for the National Youth Employment Program, offering vocational training and job placement services for young Chadians aged 18-35.</p>",
    tags: ["Youth", "Employment", "Training"],
    externalLink: "https://www.africa.engineering.cmu.edu/admissions/index.html",
    publishDate: "2024-12-05T09:00:00Z",
    isPublished: true,
  },
  {
    id: 5,
    title: "Lake Chad Conservation Summit Scheduled",
    content: "<p>Chad will host the regional Lake Chad Conservation Summit in January 2025, bringing together leaders from neighboring countries to address environmental challenges and develop sustainable solutions.</p>",
    tags: ["Environment", "Conservation", "Regional"],
    publishDate: "2024-12-01T11:00:00Z",
    isPublished: true,
    externalLink: "https://www.africa.engineering.cmu.edu/admissions/index.html",

  },
  {
    id: 6,
    title: "Digital Government Services Portal Launched",
    content: "<p>Citizens can now access government services online through the new digital portal. Services include document requests, permit applications, and information access.</p>",
    tags: ["Digital", "E-Government", "Innovation"],
    externalLink: "https://www.africa.engineering.cmu.edu/admissions/index.html",
    publishDate: "2024-11-28T08:30:00Z",
    isPublished: true,
  },
];
